language: python
python: 2.7
env:
  - TOX_ENV=pep8
  - TOX_ENV=unittest
  - TOX_ENV=coverage
  - TOX_ENV=sdist
  - TOX_ENV=docs
  - TOX_ENV=pyflakes
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
